// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoBufPacket.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoBuf.ProtoBufPacket {

  /// <summary>Holder for reflection information generated from ProtoBufPacket.proto</summary>
  public static partial class ProtoBufPacketReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoBufPacket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoBufPacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm90b0J1ZlBhY2tldC5wcm90byLSAQoMUGF5bG9hZENsYXNzEhAKCGFw",
            "cFJ1bk9TGAEgASgFEg8KB2FwcE5hbWUYAiABKAkSEgoKYXBwVmVyc2lvbhgD",
            "IAEoCRISCgpjdXJyZW50VVRDGAQgASgDEhAKCHVzZXJVVUlEGAUgASgJEiEK",
            "C3JlcXVlc3RDb2RlGAYgASgOMgwuUGF5bG9hZFR5cGUSEwoLcmVxdWVzdERh",
            "dGEYByABKAwSFQoNcmVzdWx0TWVzc2FnZRgIIAEoCRIWCg5icm9hZENhc3RH",
            "cm91cBgJIAEoBSIpChVQYXlsb2FkQ2xhc3NVc2VyRW50ZXISEAoIdXNlck5h",
            "bWUYASABKAkicAoXUGF5bG9hZENsYXNzUm9vbXNTZWFyY2gSDwoHcm9vbVNl",
            "cRgBIAEoBRIQCghyb29tVHlwZRgCIAEoBRIYChByb29tTm93UGVyc29ubmVs",
            "GAMgASgFEhgKEHJvb21NYXhQZXJzb25uZWwYBCABKAUiOwoWUGF5bG9hZENs",
            "YXNzUm9vbUNyZWF0ZRIPCgdyb29tU2VxGAEgASgFEhAKCHJvb21UeXBlGAIg",
            "ASgFIjkKFFBheWxvYWRDbGFzc1Jvb21Kb2luEg8KB3Jvb21TZXEYASABKAUS",
            "EAoIcm9vbVR5cGUYAiABKAUiOQoUUGF5bG9hZENsYXNzUm9vbVF1aXQSDwoH",
            "cm9vbVNlcRgBIAEoBRIQCghyb29tVHlwZRgCIAEoBSrFAQoLUGF5bG9hZFR5",
            "cGUSCwoHQXBwSW5pdBAAEhMKD0FwcFZlcnNpb25DaGVjaxABEhEKDUFwcEN1",
            "cnJlbnRVVEMQAhIQCgxBcHBSZWNvbm5lY3QQAxIRCg1BcHBEaXNjb25uZWN0",
            "EAQSCwoHQXBwUXVpdBAFEg4KCVVzZXJFbnRlchDpBxIQCgtSb29tc1NlYXJj",
            "aBDRDxIPCgpSb29tQ3JlYXRlENIPEg0KCFJvb21Kb2luENMPEg0KCFJvb21R",
            "dWl0ENQPQjNaF1Byb3RvQnVmL1Byb3RvQnVmUGFja2V0qgIXUHJvdG9CdWYu",
            "UHJvdG9CdWZQYWNrZXRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtoBuf.ProtoBufPacket.PayloadType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBuf.ProtoBufPacket.PayloadClass), global::ProtoBuf.ProtoBufPacket.PayloadClass.Parser, new[]{ "AppRunOS", "AppName", "AppVersion", "CurrentUTC", "UserUUID", "RequestCode", "RequestData", "ResultMessage", "BroadCastGroup" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBuf.ProtoBufPacket.PayloadClassUserEnter), global::ProtoBuf.ProtoBufPacket.PayloadClassUserEnter.Parser, new[]{ "UserName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBuf.ProtoBufPacket.PayloadClassRoomsSearch), global::ProtoBuf.ProtoBufPacket.PayloadClassRoomsSearch.Parser, new[]{ "RoomSeq", "RoomType", "RoomNowPersonnel", "RoomMaxPersonnel" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBuf.ProtoBufPacket.PayloadClassRoomCreate), global::ProtoBuf.ProtoBufPacket.PayloadClassRoomCreate.Parser, new[]{ "RoomSeq", "RoomType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBuf.ProtoBufPacket.PayloadClassRoomJoin), global::ProtoBuf.ProtoBufPacket.PayloadClassRoomJoin.Parser, new[]{ "RoomSeq", "RoomType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBuf.ProtoBufPacket.PayloadClassRoomQuit), global::ProtoBuf.ProtoBufPacket.PayloadClassRoomQuit.Parser, new[]{ "RoomSeq", "RoomType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// PayloadType 열거형 정의
  /// </summary>
  public enum PayloadType {
    /// <summary>
    /// 어플 관련
    /// </summary>
    [pbr::OriginalName("AppInit")] AppInit = 0,
    [pbr::OriginalName("AppVersionCheck")] AppVersionCheck = 1,
    [pbr::OriginalName("AppCurrentUTC")] AppCurrentUtc = 2,
    [pbr::OriginalName("AppReconnect")] AppReconnect = 3,
    [pbr::OriginalName("AppDisconnect")] AppDisconnect = 4,
    [pbr::OriginalName("AppQuit")] AppQuit = 5,
    /// <summary>
    /// 유저 관련
    /// </summary>
    [pbr::OriginalName("UserEnter")] UserEnter = 1001,
    /// <summary>
    /// 방 관련
    /// </summary>
    [pbr::OriginalName("RoomsSearch")] RoomsSearch = 2001,
    [pbr::OriginalName("RoomCreate")] RoomCreate = 2002,
    [pbr::OriginalName("RoomJoin")] RoomJoin = 2003,
    [pbr::OriginalName("RoomQuit")] RoomQuit = 2004,
  }

  #endregion

  #region Messages
  /// <summary>
  /// PayloadClass 메시지 정의
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PayloadClass : pb::IMessage<PayloadClass>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayloadClass> _parser = new pb::MessageParser<PayloadClass>(() => new PayloadClass());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayloadClass> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoBuf.ProtoBufPacket.ProtoBufPacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClass() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClass(PayloadClass other) : this() {
      appRunOS_ = other.appRunOS_;
      appName_ = other.appName_;
      appVersion_ = other.appVersion_;
      currentUTC_ = other.currentUTC_;
      userUUID_ = other.userUUID_;
      requestCode_ = other.requestCode_;
      requestData_ = other.requestData_;
      resultMessage_ = other.resultMessage_;
      broadCastGroup_ = other.broadCastGroup_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClass Clone() {
      return new PayloadClass(this);
    }

    /// <summary>Field number for the "appRunOS" field.</summary>
    public const int AppRunOSFieldNumber = 1;
    private int appRunOS_;
    /// <summary>
    /// App에 관한 정보
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AppRunOS {
      get { return appRunOS_; }
      set {
        appRunOS_ = value;
      }
    }

    /// <summary>Field number for the "appName" field.</summary>
    public const int AppNameFieldNumber = 2;
    private string appName_ = "";
    /// <summary>
    /// 2. 애플리케이션 이름
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppName {
      get { return appName_; }
      set {
        appName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "appVersion" field.</summary>
    public const int AppVersionFieldNumber = 3;
    private string appVersion_ = "";
    /// <summary>
    /// 3. 애플리케이션 버전 .. 버전 정보는 일반적으로 "메이저.마이너.패치"와 같은 형식
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppVersion {
      get { return appVersion_; }
      set {
        appVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "currentUTC" field.</summary>
    public const int CurrentUTCFieldNumber = 4;
    private long currentUTC_;
    /// <summary>
    /// Time에 관한 정보
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CurrentUTC {
      get { return currentUTC_; }
      set {
        currentUTC_ = value;
      }
    }

    /// <summary>Field number for the "userUUID" field.</summary>
    public const int UserUUIDFieldNumber = 5;
    private string userUUID_ = "";
    /// <summary>
    /// User에 관한 정보
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserUUID {
      get { return userUUID_; }
      set {
        userUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "requestCode" field.</summary>
    public const int RequestCodeFieldNumber = 6;
    private global::ProtoBuf.ProtoBufPacket.PayloadType requestCode_ = global::ProtoBuf.ProtoBufPacket.PayloadType.AppInit;
    /// <summary>
    /// 데이터에 관한 정보
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoBuf.ProtoBufPacket.PayloadType RequestCode {
      get { return requestCode_; }
      set {
        requestCode_ = value;
      }
    }

    /// <summary>Field number for the "requestData" field.</summary>
    public const int RequestDataFieldNumber = 7;
    private pb::ByteString requestData_ = pb::ByteString.Empty;
    /// <summary>
    /// 7. 요청 데이터 (바이트 배열)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString RequestData {
      get { return requestData_; }
      set {
        requestData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resultMessage" field.</summary>
    public const int ResultMessageFieldNumber = 8;
    private string resultMessage_ = "";
    /// <summary>
    /// 8. 결과 메세지
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResultMessage {
      get { return resultMessage_; }
      set {
        resultMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "broadCastGroup" field.</summary>
    public const int BroadCastGroupFieldNumber = 9;
    private int broadCastGroup_;
    /// <summary>
    /// 9. 방 번호 // 방 입장 전엔 0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BroadCastGroup {
      get { return broadCastGroup_; }
      set {
        broadCastGroup_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayloadClass);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayloadClass other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AppRunOS != other.AppRunOS) return false;
      if (AppName != other.AppName) return false;
      if (AppVersion != other.AppVersion) return false;
      if (CurrentUTC != other.CurrentUTC) return false;
      if (UserUUID != other.UserUUID) return false;
      if (RequestCode != other.RequestCode) return false;
      if (RequestData != other.RequestData) return false;
      if (ResultMessage != other.ResultMessage) return false;
      if (BroadCastGroup != other.BroadCastGroup) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AppRunOS != 0) hash ^= AppRunOS.GetHashCode();
      if (AppName.Length != 0) hash ^= AppName.GetHashCode();
      if (AppVersion.Length != 0) hash ^= AppVersion.GetHashCode();
      if (CurrentUTC != 0L) hash ^= CurrentUTC.GetHashCode();
      if (UserUUID.Length != 0) hash ^= UserUUID.GetHashCode();
      if (RequestCode != global::ProtoBuf.ProtoBufPacket.PayloadType.AppInit) hash ^= RequestCode.GetHashCode();
      if (RequestData.Length != 0) hash ^= RequestData.GetHashCode();
      if (ResultMessage.Length != 0) hash ^= ResultMessage.GetHashCode();
      if (BroadCastGroup != 0) hash ^= BroadCastGroup.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AppRunOS != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AppRunOS);
      }
      if (AppName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AppName);
      }
      if (AppVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppVersion);
      }
      if (CurrentUTC != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(CurrentUTC);
      }
      if (UserUUID.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(UserUUID);
      }
      if (RequestCode != global::ProtoBuf.ProtoBufPacket.PayloadType.AppInit) {
        output.WriteRawTag(48);
        output.WriteEnum((int) RequestCode);
      }
      if (RequestData.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(RequestData);
      }
      if (ResultMessage.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ResultMessage);
      }
      if (BroadCastGroup != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(BroadCastGroup);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AppRunOS != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AppRunOS);
      }
      if (AppName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AppName);
      }
      if (AppVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppVersion);
      }
      if (CurrentUTC != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(CurrentUTC);
      }
      if (UserUUID.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(UserUUID);
      }
      if (RequestCode != global::ProtoBuf.ProtoBufPacket.PayloadType.AppInit) {
        output.WriteRawTag(48);
        output.WriteEnum((int) RequestCode);
      }
      if (RequestData.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(RequestData);
      }
      if (ResultMessage.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ResultMessage);
      }
      if (BroadCastGroup != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(BroadCastGroup);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AppRunOS != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AppRunOS);
      }
      if (AppName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppName);
      }
      if (AppVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppVersion);
      }
      if (CurrentUTC != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CurrentUTC);
      }
      if (UserUUID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserUUID);
      }
      if (RequestCode != global::ProtoBuf.ProtoBufPacket.PayloadType.AppInit) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestCode);
      }
      if (RequestData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RequestData);
      }
      if (ResultMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResultMessage);
      }
      if (BroadCastGroup != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BroadCastGroup);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayloadClass other) {
      if (other == null) {
        return;
      }
      if (other.AppRunOS != 0) {
        AppRunOS = other.AppRunOS;
      }
      if (other.AppName.Length != 0) {
        AppName = other.AppName;
      }
      if (other.AppVersion.Length != 0) {
        AppVersion = other.AppVersion;
      }
      if (other.CurrentUTC != 0L) {
        CurrentUTC = other.CurrentUTC;
      }
      if (other.UserUUID.Length != 0) {
        UserUUID = other.UserUUID;
      }
      if (other.RequestCode != global::ProtoBuf.ProtoBufPacket.PayloadType.AppInit) {
        RequestCode = other.RequestCode;
      }
      if (other.RequestData.Length != 0) {
        RequestData = other.RequestData;
      }
      if (other.ResultMessage.Length != 0) {
        ResultMessage = other.ResultMessage;
      }
      if (other.BroadCastGroup != 0) {
        BroadCastGroup = other.BroadCastGroup;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AppRunOS = input.ReadInt32();
            break;
          }
          case 18: {
            AppName = input.ReadString();
            break;
          }
          case 26: {
            AppVersion = input.ReadString();
            break;
          }
          case 32: {
            CurrentUTC = input.ReadInt64();
            break;
          }
          case 42: {
            UserUUID = input.ReadString();
            break;
          }
          case 48: {
            RequestCode = (global::ProtoBuf.ProtoBufPacket.PayloadType) input.ReadEnum();
            break;
          }
          case 58: {
            RequestData = input.ReadBytes();
            break;
          }
          case 66: {
            ResultMessage = input.ReadString();
            break;
          }
          case 72: {
            BroadCastGroup = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AppRunOS = input.ReadInt32();
            break;
          }
          case 18: {
            AppName = input.ReadString();
            break;
          }
          case 26: {
            AppVersion = input.ReadString();
            break;
          }
          case 32: {
            CurrentUTC = input.ReadInt64();
            break;
          }
          case 42: {
            UserUUID = input.ReadString();
            break;
          }
          case 48: {
            RequestCode = (global::ProtoBuf.ProtoBufPacket.PayloadType) input.ReadEnum();
            break;
          }
          case 58: {
            RequestData = input.ReadBytes();
            break;
          }
          case 66: {
            ResultMessage = input.ReadString();
            break;
          }
          case 72: {
            BroadCastGroup = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ////////////////////////////
  ///! User
  ////////////////////////////
  /// PayloadClassUserEnder 메시지 정의 (1001)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PayloadClassUserEnter : pb::IMessage<PayloadClassUserEnter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayloadClassUserEnter> _parser = new pb::MessageParser<PayloadClassUserEnter>(() => new PayloadClassUserEnter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayloadClassUserEnter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoBuf.ProtoBufPacket.ProtoBufPacketReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassUserEnter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassUserEnter(PayloadClassUserEnter other) : this() {
      userName_ = other.userName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassUserEnter Clone() {
      return new PayloadClassUserEnter(this);
    }

    /// <summary>Field number for the "userName" field.</summary>
    public const int UserNameFieldNumber = 1;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayloadClassUserEnter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayloadClassUserEnter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserName != other.UserName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayloadClassUserEnter other) {
      if (other == null) {
        return;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ////////////////////////////
  ///! Room
  ////////////////////////////
  /// RoomsSearch 메시지 정의 (2001)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PayloadClassRoomsSearch : pb::IMessage<PayloadClassRoomsSearch>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayloadClassRoomsSearch> _parser = new pb::MessageParser<PayloadClassRoomsSearch>(() => new PayloadClassRoomsSearch());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayloadClassRoomsSearch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoBuf.ProtoBufPacket.ProtoBufPacketReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomsSearch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomsSearch(PayloadClassRoomsSearch other) : this() {
      roomSeq_ = other.roomSeq_;
      roomType_ = other.roomType_;
      roomNowPersonnel_ = other.roomNowPersonnel_;
      roomMaxPersonnel_ = other.roomMaxPersonnel_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomsSearch Clone() {
      return new PayloadClassRoomsSearch(this);
    }

    /// <summary>Field number for the "roomSeq" field.</summary>
    public const int RoomSeqFieldNumber = 1;
    private int roomSeq_;
    /// <summary>
    /// 1. 방 번호
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomSeq {
      get { return roomSeq_; }
      set {
        roomSeq_ = value;
      }
    }

    /// <summary>Field number for the "roomType" field.</summary>
    public const int RoomTypeFieldNumber = 2;
    private int roomType_;
    /// <summary>
    /// 2. 방 게임 타입
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomType {
      get { return roomType_; }
      set {
        roomType_ = value;
      }
    }

    /// <summary>Field number for the "roomNowPersonnel" field.</summary>
    public const int RoomNowPersonnelFieldNumber = 3;
    private int roomNowPersonnel_;
    /// <summary>
    /// 3. 현재 방에 몇명 있는지
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomNowPersonnel {
      get { return roomNowPersonnel_; }
      set {
        roomNowPersonnel_ = value;
      }
    }

    /// <summary>Field number for the "roomMaxPersonnel" field.</summary>
    public const int RoomMaxPersonnelFieldNumber = 4;
    private int roomMaxPersonnel_;
    /// <summary>
    /// 4. 현재 방에 몇명 참여 가능한지
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomMaxPersonnel {
      get { return roomMaxPersonnel_; }
      set {
        roomMaxPersonnel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayloadClassRoomsSearch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayloadClassRoomsSearch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomSeq != other.RoomSeq) return false;
      if (RoomType != other.RoomType) return false;
      if (RoomNowPersonnel != other.RoomNowPersonnel) return false;
      if (RoomMaxPersonnel != other.RoomMaxPersonnel) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomSeq != 0) hash ^= RoomSeq.GetHashCode();
      if (RoomType != 0) hash ^= RoomType.GetHashCode();
      if (RoomNowPersonnel != 0) hash ^= RoomNowPersonnel.GetHashCode();
      if (RoomMaxPersonnel != 0) hash ^= RoomMaxPersonnel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomSeq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomSeq);
      }
      if (RoomType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoomType);
      }
      if (RoomNowPersonnel != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RoomNowPersonnel);
      }
      if (RoomMaxPersonnel != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RoomMaxPersonnel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomSeq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomSeq);
      }
      if (RoomType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoomType);
      }
      if (RoomNowPersonnel != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RoomNowPersonnel);
      }
      if (RoomMaxPersonnel != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RoomMaxPersonnel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomSeq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomSeq);
      }
      if (RoomType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomType);
      }
      if (RoomNowPersonnel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomNowPersonnel);
      }
      if (RoomMaxPersonnel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomMaxPersonnel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayloadClassRoomsSearch other) {
      if (other == null) {
        return;
      }
      if (other.RoomSeq != 0) {
        RoomSeq = other.RoomSeq;
      }
      if (other.RoomType != 0) {
        RoomType = other.RoomType;
      }
      if (other.RoomNowPersonnel != 0) {
        RoomNowPersonnel = other.RoomNowPersonnel;
      }
      if (other.RoomMaxPersonnel != 0) {
        RoomMaxPersonnel = other.RoomMaxPersonnel;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomSeq = input.ReadInt32();
            break;
          }
          case 16: {
            RoomType = input.ReadInt32();
            break;
          }
          case 24: {
            RoomNowPersonnel = input.ReadInt32();
            break;
          }
          case 32: {
            RoomMaxPersonnel = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomSeq = input.ReadInt32();
            break;
          }
          case 16: {
            RoomType = input.ReadInt32();
            break;
          }
          case 24: {
            RoomNowPersonnel = input.ReadInt32();
            break;
          }
          case 32: {
            RoomMaxPersonnel = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// RoomJoin 메시지 정의 (2002)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PayloadClassRoomCreate : pb::IMessage<PayloadClassRoomCreate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayloadClassRoomCreate> _parser = new pb::MessageParser<PayloadClassRoomCreate>(() => new PayloadClassRoomCreate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayloadClassRoomCreate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoBuf.ProtoBufPacket.ProtoBufPacketReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomCreate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomCreate(PayloadClassRoomCreate other) : this() {
      roomSeq_ = other.roomSeq_;
      roomType_ = other.roomType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomCreate Clone() {
      return new PayloadClassRoomCreate(this);
    }

    /// <summary>Field number for the "roomSeq" field.</summary>
    public const int RoomSeqFieldNumber = 1;
    private int roomSeq_;
    /// <summary>
    /// 1. 방 번호
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomSeq {
      get { return roomSeq_; }
      set {
        roomSeq_ = value;
      }
    }

    /// <summary>Field number for the "roomType" field.</summary>
    public const int RoomTypeFieldNumber = 2;
    private int roomType_;
    /// <summary>
    /// 2. 방 게임 타입
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomType {
      get { return roomType_; }
      set {
        roomType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayloadClassRoomCreate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayloadClassRoomCreate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomSeq != other.RoomSeq) return false;
      if (RoomType != other.RoomType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomSeq != 0) hash ^= RoomSeq.GetHashCode();
      if (RoomType != 0) hash ^= RoomType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomSeq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomSeq);
      }
      if (RoomType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoomType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomSeq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomSeq);
      }
      if (RoomType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoomType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomSeq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomSeq);
      }
      if (RoomType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayloadClassRoomCreate other) {
      if (other == null) {
        return;
      }
      if (other.RoomSeq != 0) {
        RoomSeq = other.RoomSeq;
      }
      if (other.RoomType != 0) {
        RoomType = other.RoomType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomSeq = input.ReadInt32();
            break;
          }
          case 16: {
            RoomType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomSeq = input.ReadInt32();
            break;
          }
          case 16: {
            RoomType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// RoomJoin 메시지 정의 (2002)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PayloadClassRoomJoin : pb::IMessage<PayloadClassRoomJoin>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayloadClassRoomJoin> _parser = new pb::MessageParser<PayloadClassRoomJoin>(() => new PayloadClassRoomJoin());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayloadClassRoomJoin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoBuf.ProtoBufPacket.ProtoBufPacketReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomJoin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomJoin(PayloadClassRoomJoin other) : this() {
      roomSeq_ = other.roomSeq_;
      roomType_ = other.roomType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomJoin Clone() {
      return new PayloadClassRoomJoin(this);
    }

    /// <summary>Field number for the "roomSeq" field.</summary>
    public const int RoomSeqFieldNumber = 1;
    private int roomSeq_;
    /// <summary>
    /// 1. 방 번호
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomSeq {
      get { return roomSeq_; }
      set {
        roomSeq_ = value;
      }
    }

    /// <summary>Field number for the "roomType" field.</summary>
    public const int RoomTypeFieldNumber = 2;
    private int roomType_;
    /// <summary>
    /// 2. 방 게임 타입
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomType {
      get { return roomType_; }
      set {
        roomType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayloadClassRoomJoin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayloadClassRoomJoin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomSeq != other.RoomSeq) return false;
      if (RoomType != other.RoomType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomSeq != 0) hash ^= RoomSeq.GetHashCode();
      if (RoomType != 0) hash ^= RoomType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomSeq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomSeq);
      }
      if (RoomType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoomType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomSeq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomSeq);
      }
      if (RoomType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoomType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomSeq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomSeq);
      }
      if (RoomType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayloadClassRoomJoin other) {
      if (other == null) {
        return;
      }
      if (other.RoomSeq != 0) {
        RoomSeq = other.RoomSeq;
      }
      if (other.RoomType != 0) {
        RoomType = other.RoomType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomSeq = input.ReadInt32();
            break;
          }
          case 16: {
            RoomType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomSeq = input.ReadInt32();
            break;
          }
          case 16: {
            RoomType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// RoomQuit 메시지 정의 (2003)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PayloadClassRoomQuit : pb::IMessage<PayloadClassRoomQuit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayloadClassRoomQuit> _parser = new pb::MessageParser<PayloadClassRoomQuit>(() => new PayloadClassRoomQuit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayloadClassRoomQuit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoBuf.ProtoBufPacket.ProtoBufPacketReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomQuit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomQuit(PayloadClassRoomQuit other) : this() {
      roomSeq_ = other.roomSeq_;
      roomType_ = other.roomType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassRoomQuit Clone() {
      return new PayloadClassRoomQuit(this);
    }

    /// <summary>Field number for the "roomSeq" field.</summary>
    public const int RoomSeqFieldNumber = 1;
    private int roomSeq_;
    /// <summary>
    /// 1. 방 번호
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomSeq {
      get { return roomSeq_; }
      set {
        roomSeq_ = value;
      }
    }

    /// <summary>Field number for the "roomType" field.</summary>
    public const int RoomTypeFieldNumber = 2;
    private int roomType_;
    /// <summary>
    /// 2. 방 게임 타입
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomType {
      get { return roomType_; }
      set {
        roomType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayloadClassRoomQuit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayloadClassRoomQuit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomSeq != other.RoomSeq) return false;
      if (RoomType != other.RoomType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomSeq != 0) hash ^= RoomSeq.GetHashCode();
      if (RoomType != 0) hash ^= RoomType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomSeq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomSeq);
      }
      if (RoomType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoomType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomSeq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomSeq);
      }
      if (RoomType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoomType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomSeq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomSeq);
      }
      if (RoomType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayloadClassRoomQuit other) {
      if (other == null) {
        return;
      }
      if (other.RoomSeq != 0) {
        RoomSeq = other.RoomSeq;
      }
      if (other.RoomType != 0) {
        RoomType = other.RoomType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomSeq = input.ReadInt32();
            break;
          }
          case 16: {
            RoomType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomSeq = input.ReadInt32();
            break;
          }
          case 16: {
            RoomType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
